# TORCH.AUTOGRAD를 사용한 자동 미분

In [1]:
import torch

In [2]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

## Tensor, Function과 연산그래프(Computational graph)

In [5]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")


Gradient function for z = <AddBackward0 object at 0x000001784AB54B20>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001784AB54E20>


## 변화도(Gradient) 계산하기

In [6]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0945, 0.0621, 0.0672],
        [0.0945, 0.0621, 0.0672],
        [0.0945, 0.0621, 0.0672],
        [0.0945, 0.0621, 0.0672],
        [0.0945, 0.0621, 0.0672]])
tensor([0.0945, 0.0621, 0.0672])


## 변화도 추적 멈추기

In [7]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

True


In [8]:
with torch.no_grad():
    z = torch.matmul(x, w) + b
print(z.requires_grad)

False


In [9]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


## 선택적으로 읽기(Optional Reading): 텐서 변화도와 야코비안 곱 (Jacobian Product)

In [20]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp + 1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First cal\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"Second cal\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")


First cal
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
Second cal
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
